def format(): 
  template = {'New File Template':{'Addons': ['',
  ',value = False',
  '',
  '',
  '',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False'],
 'Condition': [True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True],
 'Question': ['CL92 Due Date (add 10 days):',
  'Coverage issues:',
  'Risk/Loss:',
  "Recd date:",
  'Need RI from: ',
  'Need to open exposures and reserve lines    ',
  'Need to rule out PDX (use PDX Add on if applies)    ',
  'Need to rule out MIP (use MIP Add on if applies)   ',
  'Need to start/unbypass Claim IQ (status view)   ',
  'Need to verify perm use   ',
  'Need to advise Named insrd of 1st/3rd    ',
  'Need to advise BI process to Named insrd   ',
  'Need to advise insured driver of 3rd party covg  ',
  'Need to advise BI process to insrd driver/inj party   ',
  'Need to VNI/VNP/VNM Insured    ',
  'Need to update 1st contact Indicator for Insrd   (Email/Injury Indicator/Cass Verify)\xa0  ',
  'Need to set ICD-10/No Fault Limit/Cause/Eligibility   ',
  'Need to VNI/VNP/VNM Clmnt    ',
  'Need to advise BI process to clmt/inj party   ',
  'Need to update 1st contact Indicator for Clmt   (Email/Injury Indicator/Cass Verify)\xa0    ',
  'Need to set ICD-10/No Fault Limit/Cause/Eligibility   ',
  'Need to send general contact letter   ',
  'Need to complete Claim IQ   ',
  'Need to Doc reason/approval for liab in NOTES   ',
  'Need to advise Named insrd of liability   ',
  'Need to advise insrd Driver of liability    ',
  'Need to advise clmnt/d of liability    ',
  'Need to advise clmnt owner of liability   ',
  'Need to Send Clmnt/O liability letter(cc A/C)   ',
  'Need to Send Clmnt/D liability letter   ',
  'Need to set Handling Complete    ',
  'Need to Send SL71/72',
  'Need to Send OR specific letters(OR advance pay/ OR_Agreement_to_PIP_UM_Arbitration (EC0311)  ',
  'Need to run ISO   ',
  'Need to send out Med auths/HI Tech    ',
  'Need to secure Medicare 4/let sent   '],
 'Type': ['date_input',
  'checkbox',
  'text_input',
  'date_input',
  'text_input',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox']},
            'Inherited File Template':{'Addons': [',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  '',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  '',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  '',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ''],
 'Condition': [True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  'responses[23]',
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True],
 'Question': ['Tipped PH:',
  'Tipped PH/D:',
  'Tipped CLMT:',
  'Tipped CLMT/D:',
  'Coverage/Limit Issues:',
  'Exposures Open:',
  'FOA & L/D- rvwd for comp neg:',
  'ADV LIABILITY NI-PH:',
  'ADV LIABILITY D-CLMT:',
  'ADV FPC/TPC/BI Covg NI-:',
  'ADV FPC/TPC/BI Covg PH/D:',
  'ADV BI PROCESS NI-PH:',
  'ADV BI PROCESS D-CLMT:',
  'PEND RI(S)?',
  'Reasoning for RI denial:',
  'VNI/VNP/VNM Pending for:',
  'Injury Status/ICD10/MED4 Updated?:',
  'SL71/72 sent?:',
  'OR specific letters(OR advance pay/ OR_Agreement_to_PIP_UM_Arbitration (EC0311):',
  'Med Auths Sent?:',
  'ISO Results:',
  'Is CIQ correct?',
  'Was prev bypass for loi/fcs?',
  'Have record been received?',
  'see PIP Tab, unable to add FPM',
  'Specials updated?',
  'Diagnosis?',
  'records exchange?',
  'Venue?',
  'Reserves Appropriate?:',
  'What is Needed to Close each',
  'EXPOSURE CL92:',
  'EXPOSURE AOB/ABP updated:',
  'CONTACT A/C',
  'req copy of ledger',
  'PIP PTD',
  'Last DOS paid:'],
 'Type': ['checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'text_input',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'write',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'text_input',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'date_input']},
            'Docusign Atlas Notes Template':{'Addons': [', value = False',
  ',value = False',
  ',value = False',
  '',
  '',
  '',
  ',value = False'],
 'Condition': [True, True, True, True, True, True, True],
 'Question': ['Offered: (yes/no)',
  'Accepted: (yes/no)',
  'Access code provided: (yes/no)',
  'Email addresses (copy/paste or N/A):',
  'Atty’s:',
  'Signers’:',
  'SharePoint request submitted: (yes/no)'],
 'Type': ['checkbox',
  'checkbox',
  'checkbox',
  'text_input',
  'text_input',
  'text_input',
  'checkbox']},
            'Atty 1st Contact Template':{'Addons': [',value = False',
  ',value = False',
  '',
  '',
  '',
  '',
  ',value = False',
  ',value = False',
  '',
  '',
  ',value = False',
  ',value = False',
  '',
  '',
  '',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  '',
  ',value = False'],
 'Condition': [True,
  True,
  True,
  True,
  True,
  True,
  True,
  'responses[6]',
  'not(responses[7])',
  True,
  True,
  True,
  'responses[9]',
  'responses[9]',
  'responses[9]',
  True,
  True,
  'responses[14]',
  'responses[14]',
  True,
  True,
  True,
  True],
 'Question': ['TCR2- Atty 1st ctc',
  'Atty TIN updated in parties?',
  'Full name of person you spoke with from atty office -',
  'Ip Full Info:',
  'SSN/DOB#-   ',
  'Injuries-   ',
  'ER:    ',
  'ER (on DOL?):    ',
  'What Date ER?',
  'Dx testing:',
  'Occupation:   w/l?',
  'Client Still T/X?:',
  'Tx type,',
  'freq of tx,',
  'Approx. med specials   ',
  'A/C Info For PIP:  ',
  'LOR on file?:  ',
  'IF LOR ON FILE ADV COVG',
  'IF LOR ON FILE ADV LIAB',
  'PR:   ',
  'Can I Take Statement from IP ?',
  'Passengers: Names? Minors?',
  'Claiming damages? Inspection?'],
 'Type': ['checkbox',
  'checkbox',
  'text_input',
  'text_input',
  'text_input',
  'text_input',
  'checkbox',
  'checkbox',
  'date_input',
  'text_input',
  'checkbox',
  'checkbox',
  'text_input',
  'text_input',
  'text_input',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'text_input',
  'checkbox']},
            'Transfer Between Unrepped and Repped Template':{'Addons': ['',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ''],
 'Condition': [True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True],
 'Question': ['FOA:',
  'Liability Resolved:',
  'Coverage Issues:',
  'PDX Status:',
  'Exposures Needed:',
  'Treatment Received:',
  'CIQ Updated/Completed:',
  'ISO RUN:',
  'TRRs Completed:',
  'Correspondence Handled:',
  'Docs Classified:',
  'Customer Log Updated:',
  'Additional Concerns:'],
 'Type': ['text_input',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'text_input']},
            'Advanced Authority Template':{'Addons': ['', '', ''],
 'Condition': [True, True, True],
 'Question': ['AA \xa0Amount:', 'AA \xa0Date:', 'Who Gave AA:'],
 'Type': ['text_input', 'date_input', 'text_input']},
            'Out of Region Template':{'Addons': ['',
  '',
  '',
  ',value = False',
  '',
  '',
  '',
  ',value = False',
  ',value = False'],
 'Condition': [True,
  True,
  True,
  True,
  'responses[3]',
  'responses[3]',
  'responses[3]',
  True,
  True],
 'Question': ['Risk State:',
  'Loss State:',
  'CC Codes:\xa0',
  'Injuries:',
  "If inj, which IPs are inj:",
  'If inj, where is tx taking place:',
  'If inj, are inj parties RR of named insured:',
  'Any indication of UM:',
  'PIP or Med Pay on policy:'],
 'Type': ['text_input',
  'text_input',
  'text_input',
  'checkbox',
  'text_input',
  'text_input',
  'text_input',
  'checkbox',
  'checkbox']},
            'CU Transfer Template':{'Addons': ['',
  '',
  '',
  '',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  '',
  '',
  '',
  '',
  '',
  '',
  ',value = False'],
 'Condition': [True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  'responses[8]',
  'responses[8]',
  'responses[8]',
  'responses[8]',
  'responses[8]',
  'responses[8]',
  'responses[8]'],
 'Question': ['Foa:',
  'Who is injured:',
  'Summary of Treatment:',
  'Reason for Transfer:',
  'Has the feature been opened:',
  'Has ISO been sent:',
  'Are all documents sorted properly:',
  'CIQ:',
  'if CIQ previously bypassed does it need to be unbypassed?',
  'Litigation Claim?',
  'Who was served:',
  'Method of Service:',
  'Date of Service:',
  'Case Number:',
  'County:',
  'Court Type:',
  'Did you advise the party to send a copy of the suit paperwork to GEICO:'],
 'Type': ['text_input',
  'text_input',
  'text_input',
  'text_input',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'text_input',
  'text_input',
  'text_input',
  'text_input',
  'text_input',
  'text_input',
  'checkbox']},
            'Arb Notice Recieved Template':{'Addons': ['',
  '',
  '',
  '',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  '',
  ''],
 'Condition': [True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True],
 'Question': ['Claim# :',
  'Risk/Loss :',
  'Injured Party :',
  'Type of Arb :',
  'Represented :',
  'PIP/MED Carrier (added to file with correct address?) :',
  'Lien in dispute :',
  'Reserves/Reopen :',
  'MIP/Biomech? :',
  'Billing Review Needed? :',
  'Peer review needed? :',
  'Transcriptions ordered? :',
  'Police report :',
  'Recommendation/notes by adjuster :',
  'Recommendation/notes by Supervisor :'],
 'Type': ['text_input',
  'text_input',
  'text_input',
  'text_input',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'text_input',
  'text_input']},
            'Misassigned Template':{'Addons': ['', '', '', '', '', '', ',value = False'],
 'Condition': [True, True, True, True, True, True, True],
 'Question': ['Claim Number:',
  'Reason for Misassign:',
  'Adjuster:',
  'Supervisor:',
  'Level:',
  'Office/Region:',
  'Documents Filed Properly?:'],
 'Type': ['text_input',
  'text_input',
  'text_input',
  'text_input',
  'text_input',
  'text_input',
  'checkbox']},
            'MIP Template':{'Addons': [',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  '',
  ',value = False',
  '',
  ',value = False',
  '',
  ',value = False',
  '',
  ',value = False',
  ',value = False',
  ',value = False',
  ''],
 'Condition': [True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True],
 'Question': ["Amount of insureds vehicle Damages:",
  "Insureds pics in file:",
  'R/I in file:',
  'Insd position on mip:',
  "Amount of claimants Damage:",
  "Claimants pics in file:  ",
  'FOA:',
  'Atty involvement:',
  'Injuries being claimed and treatment being received:',
  'Previous HX/ISO:     ',
  'Aggravating Circumstances:',
  'Date of loss treatment?',
  'Injuries reported on the police report?',
  'Biomechanical/Black Box/AX recreation?',
  'Examiner recommendations:'],
 'Type': ['checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'text_input',
  'checkbox',
  'text_input',
  'checkbox',
  'text_input',
  'checkbox',
  'text_input',
  'checkbox',
  'checkbox',
  'checkbox',
  'text_input']},
            'Liability Review Template':{'Addons': [',value = False',
  '',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False'],
 'Condition': [True, True, True, True, True, True],
 'Question': ['SBS REVIEW NEEDED?: ',
  'INSURED FOA: ',
  'EVIDENCE TO DISPROVE?',
  'WITNESSES?: ',
  'SECURED ALL STMTS?:',
  'CIQ COMPLETED?: '],
 'Type': ['checkbox',
  'text_input',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox']},
            'MED RI MIP Questions':{'Addons': ['',
  ',value = False',
  '',
  '',
  '',
  '',
  '',
  ',value = False',
  ',value = False'],
 'Condition': [True, True, True, True, True, True, True, True, True],
 'Question': ['What was the position of all occupants in the vehicle?',
  'Were any objects disturbed?',
  'When did the onset of injury occur?',
  'When was the first date of treatment?',
  'Where was treatment sought?',
  'How were you referred to treating provider?',
  'Any history of injuries? Were they resolved prior to the loss occurring?',
  'did they turn head/see other driver at impact?',
  'body oriented in strange position?'],
 'Type': ['text_input',
  'checkbox',
  'date_input',
  'date_input',
  'text_input',
  'text_input',
  'text_input',
  'checkbox',
  'checkbox']},
            'Closing File Template':{'Addons': [',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False'],
 'Condition': [True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True],
 'Question': ['Tip Complete all parties?',
  'Cov Explained/Issue?',
  'Liability Advised?',
  "VNId all Parties?",
  'Verify Pssngrs?',
  'Any minors involved?',
  'CIQ Liab Started/Completed?',
  'CIQ Inj Started / Completed?',
  'Reserves Opened?',
  'H/C set?',
  'ISO documented?',
  'Stmts taken?',
  'Med Forms Sent?',
  'FCS attempted?',
  'MIP?',
  'MIP Denial Sent?',
  'Liability Set?',
  'Liability Denial Sent?',
  'CL92s sent?',
  'PD/BI Excess?',
  'SUBRO?',
  'Injury Indicator updated?',
  'ICD-10 updated?',
  'Release on file?',
  'CIQ updated for FCS?',
  'CIQ bypassed for FCS?',
  'CIQ bypassed for LOI?',
  'ClaimIQ completed?',
  'DOCUMENTS labeled and classifed?'],
 'Type': ['checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox']},
            'UM Validation Template':{'Addons': [',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ''],
 'Condition': [True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  'not(responses[10])'],
 'Question': ['Has contact with clmt/owner been attempted (2 calls and a letter):',
  'Has contact with clmt/driver been attempted (2 calls and a letter):',
  'ISO searches complete on clmt/owner:',
  'ISO searches complete on clmt/driver:',
  'Carrier discovery ran for owner:',
  'Carrier discovery ran for driver:',
  'Carrier discovery ran by VIN:',
  'Confirmed no insurance for clmt/owner:',
  'Confirmed no insurance for clmt/driver:',
  'Denial from a/c received (verbal confirmation okay as long as we request copy of letter):',
  'Police report filed and requested',
  'if no, please explain:'],
 'Type': ['checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'text_input']},
            'Advanced Deductable Template':{'Questions':[],
                                 'Type':[],
                                'Addons':[],
                                'Conditions':[]},
            'MIP Add On Template':{'Questions':[],
                                 'Type':[],
                                'Addons':[],
                                'Conditions':[]},
            'PDX Add On Template':{'Questions':[],
                                 'Type':[],
                                'Addons':[],
                                'Conditions':[]},
            'CC37 Add On Template':{'Questions':[],
                                 'Type':[],
                                'Addons':[],
                                'Conditions':[]},
            'Fatal CC Add On Template':{'Questions':[],
                                 'Type':[],
                                'Addons':[],
                                'Conditions':[]}
           }
  return template

