def format(): 
  template = {'Test': {'Question':['How are you?','Are you a human?','How many?'],
                    'Type':['text_input','checkbox','number_input'],
                    'Addons':['',',value = False',',min_value = 1, max_value = 10,step = 1'],
                    'Condition':[True,True,'responses[1]']},
            'New File Template':{'Addons': ['',
  ',value = False',
  '',
  '',
  '',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False'],
 'Condition': [True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True],
 'Question': ['CL92 Due Date (add 10 days):',
  'Coverage issues:',
  'Risk/Loss:',
  "Recd date:",
  'Need RI from: ',
  'Need to open exposures and reserve lines    ',
  'Need to rule out PDX (use PDX Add on if applies)    ',
  'Need to rule out MIP (use MIP Add on if applies)   ',
  'Need to start/unbypass Claim IQ (status view)   ',
  'Need to verify perm use   ',
  'Need to advise Named insrd of 1st/3rd    ',
  'Need to advise BI process to Named insrd   ',
  'Need to advise insured driver of 3rd party covg  ',
  'Need to advise BI process to insrd driver/inj party   ',
  'Need to VNI/VNP/VNM Insured    ',
  'Need to update 1st contact Indicator for Insrd   (Email/Injury Indicator/Cass Verify)\xa0  ',
  'Need to set ICD-10/No Fault Limit/Cause/Eligibility   ',
  'Need to VNI/VNP/VNM Clmnt    ',
  'Need to advise BI process to clmt/inj party   ',
  'Need to update 1st contact Indicator for Clmt   (Email/Injury Indicator/Cass Verify)\xa0    ',
  'Need to set ICD-10/No Fault Limit/Cause/Eligibility   ',
  'Need to send general contact letter   ',
  'Need to complete Claim IQ   ',
  'Need to Doc reason/approval for liab in NOTES   ',
  'Need to advise Named insrd of liability   ',
  'Need to advise insrd Driver of liability    ',
  'Need to advise clmnt/d of liability    ',
  'Need to advise clmnt owner of liability   ',
  'Need to Send Clmnt/O liability letter(cc A/C)   ',
  'Need to Send Clmnt/D liability letter   ',
  'Need to set Handling Complete    ',
  'Need to Send SL71/72',
  'Need to Send OR specific letters(OR advance pay/ OR_Agreement_to_PIP_UM_Arbitration (EC0311)  ',
  'Need to run ISO   ',
  'Need to send out Med auths/HI Tech    ',
  'Need to secure Medicare 4/let sent   '],
 'Type': ['date_input',
  'checkbox',
  'text_input',
  'date_input',
  'text_input',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox']},
            'Inherited File Template':{'Addons': [',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  '',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  '',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  '',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ',value = False',
  ''],
 'Condition': [True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  'reponses[23]',
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True],
 'Question': ['Tipped PH:',
  'Tipped PH/D:',
  'Tipped CLMT:',
  'Tipped CLMT/D:',
  'Coverage/Limit Issues:',
  'Exposures Open:',
  'FOA & L/D- rvwd for comp neg:',
  'ADV LIABILITY NI-PH:',
  'ADV LIABILITY D-CLMT:',
  'ADV FPC/TPC/BI Covg NI-:',
  'ADV FPC/TPC/BI Covg PH/D:',
  'ADV BI PROCESS NI-PH:',
  'ADV BI PROCESS D-CLMT:',
  'PEND RI(S)?',
  'Reasoning for RI denial:',
  'VNI/VNP/VNM Pending for:',
  'Injury Status/ICD10/MED4 Updated?:',
  'SL71/72 sent?:',
  'OR specific letters(OR advance pay/ OR_Agreement_to_PIP_UM_Arbitration (EC0311):',
  'Med Auths Sent?:',
  'ISO Results:',
  'Is CIQ correct?',
  'Was prev bypass for loi/fcs?',
  'Have record been received?',
  'see PIP Tab, unable to add FPM',
  'Specials updated?',
  'Diagnosis?',
  'records exchange?',
  'Venue?',
  'Reserves Appropriate?:',
  'What is Needed to Close each',
  'EXPOSURE',
  'CL92:',
  'AOB/ABP updated:',
  'CONTACT A/C',
  'req copy of ledger',
  'PIP PTD',
  'Last DOS paid:'],
 'Type': ['checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'text_input',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'write',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'text_input',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'checkbox',
  'date_input']},
            'Docusign Atlas Notes Template':{'Addons': [', value = False',
  ',value = False',
  ',value = False',
  '',
  '',
  '',
  ',value = False'],
 'Condition': [True, True, True, True, True, True, True],
 'Question': ['Offered: (yes/no)',
  'Accepted: (yes/no)',
  'Access code provided: (yes/no)',
  'Email addresses (copy/paste or N/A):',
  'Atty’s:',
  'Signers’:',
  'SharePoint request submitted: (yes/no)'],
 'Type': ['checkbox',
  'checkbox',
  'checkbox',
  'text_input',
  'text_input',
  'text_input',
  'checkbox']},
            'Atty 1st Contact Template':{'Questions':[],
                                 'Type':[],
                                'Addons':[],
                                'Conditions':[]},
            'Transfer Between Unrepped and Repped Template':{'Questions':[],
                                 'Type':[],
                                'Addons':[],
                                'Conditions':[]},
            'Advanced Authority Template':{'Questions':[],
                                 'Type':[],
                                'Addons':[],
                                'Conditions':[]},
            'TRR Template':{'Questions':[],
                                 'Type':[],
                                'Addons':[],
                                'Conditions':[]},
            'Out of Region Template':{'Questions':[],
                                 'Type':[],
                                'Addons':[],
                                'Conditions':[]},
            'CU Transfer Template':{'Questions':[],
                                 'Type':[],
                                'Addons':[],
                                'Conditions':[]},
            'Arb Notice Recieved Template':{'Questions':[],
                                 'Type':[],
                                'Addons':[],
                                'Conditions':[]},
            'Check List After Getting Navigator':{'Questions':[],
                                 'Type':[],
                                'Addons':[],
                                'Conditions':[]},
            'Misassigned Template':{'Questions':[],
                                 'Type':[],
                                'Addons':[],
                                'Conditions':[]},
            'MIP Template':{'Questions':[],
                                 'Type':[],
                                'Addons':[],
                                'Conditions':[]},
            'Liability Review Template':{'Questions':[],
                                 'Type':[],
                                'Addons':[],
                                'Conditions':[]},
            'MED RI MIP Questions':{'Questions':[],
                                 'Type':[],
                                'Addons':[],
                                'Conditions':[]},
            'Evaluation Template':{'Questions':[],
                                 'Type':[],
                                'Addons':[],
                                'Conditions':[]},
            'Closing File Template':{'Questions':[],
                                 'Type':[],
                                'Addons':[],
                                'Conditions':[]},
            'UM Validation Template':{'Questions':[],
                                 'Type':[],
                                'Addons':[],
                                'Conditions':[]},
            'Advanced Deductable Template':{'Questions':[],
                                 'Type':[],
                                'Addons':[],
                                'Conditions':[]},
            'MIP Add On Template':{'Questions':[],
                                 'Type':[],
                                'Addons':[],
                                'Conditions':[]},
            'PDX Add On Template':{'Questions':[],
                                 'Type':[],
                                'Addons':[],
                                'Conditions':[]},
            'CC37 Add On Template':{'Questions':[],
                                 'Type':[],
                                'Addons':[],
                                'Conditions':[]},
            'Fatal CC Add On Template':{'Questions':[],
                                 'Type':[],
                                'Addons':[],
                                'Conditions':[]}
           }
  return template

